// src/App.vue
<template>
  <div id="app">
    <Header/>
    <ImageLeft img="/img/obermer.png" title="Barack Obama"/>
    <ImageRight img="/img/yonce.png" title="Beyoncé Knowles-Carter"/>
    <ImageLeft img="/img/potato-jesus.png" title="Potato Jesus"/>
    <ImageRight img="/img/the-creation-of-adam.png" title="The Creation of Adam"/>
    <ImageLeft img="/img/the-scream.png" title="The Scream"/>
    <ImageRight img="/img/mona-lisa.png" title="Mona Lisa"/>
    <Footer/>
  </div>
</template>

<script>
import Header from "./components/Header.vue";
import ImageLeft from "./components/ImageLeft.vue";
import ImageRight from "./components/ImageRight.vue";
import Footer from "./components/Footer.vue";

export default {
  name: "app",
  components: {
    Header,
    ImageLeft,
    ImageRight,
    Footer
  }
};
</script>

<style>
html {
  box-sizing: border-box;
}

*,
*:before,
*:after {
  box-sizing: inherit;
}

body {
  height: 100vh;
  width: 100vw;
  margin: 0;
}

#app {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  height: 100%;
  width: 100%;
}

@keyframes fade-in {
  0% {
    transform: translateY(250px);
    opacity: 0;
  }

  50% {
    opacity: 0;
  }

  100% {
    transform: translateY(0px);
    opacity: 1;
  }
}

@keyframes fade-in-left {
  0% {
    transform: translateX(250px);
    opacity: 0;
  }

  50% {
    opacity: 0;
  }

  100% {
    transform: translateX(0px);
    opacity: 1;
  }
}

@keyframes fade-in-right {
  0% {
    transform: translateX(-250px);
    opacity: 0;
  }

  50% {
    opacity: 0;
  }

  100% {
    transform: translateX(0px);
    opacity: 1;
  }
}

a {
  color: #a5a5a5;
  text-decoration: none;
  transition: color 0.25s ease-in-out;
}

a:hover {
  color: #eee;
}
</style>

// app/page.tsx
import Header from "../components/Header";
import Footer from "../components/Footer";
import ImageLeft from "../components/ImageLeft";
import ImageRight from "../components/ImageRight";
import obermer from "../public/img/obermer.png";
import yonce from "../public/img/yonce.png";
import potatoJesus from "../public/img/potato-jesus.png";
import creationOfAdam from "../public/img/the-creation-of-adam.png";
import theScream from "../public/img/the-scream.png";
import monaLisa from "../public/img/mona-lisa.png";

const Home = () => {
  return (
    <>
      <Header />

      <div className="content fade-in">
        <ImageLeft src={obermer} title="Barack Obama" priority={true} />
        <ImageRight src={yonce} title="Beyoncé Knowles-Carter" />
        <ImageLeft src={potatoJesus} title="Potato Jesus" />
        <ImageRight src={creationOfAdam} title="The Creation of Adam" />
        <ImageLeft src={theScream} title="The Scream" />
        <ImageRight src={monaLisa} title="Mona Lisa" />
        <Footer />
      </div>
    </>
  );
};

export default Home;
